title: Sales Data Analysis
description: |
  In this project, I utilized Excel to analyse sales data and extract valuable insights.
  I created interactive dashboards to present the findings in an easy to understand way.
  These dashboards provide an overview of sales trends and product performance, enabling data-driven decision-making.
show_downloads: true
theme: jekyll-theme-lanyon
