title: Analysis of Sales Data
description: >
  In this project, I utilized Excel to analyse sales data and extract valuable insights. <br>
  I created interactive dashboards to present the findings in an easy to understand way. <br>
  These dashboards provide an overview of sales trends and product performance, enabling data-driven decision-making.
show_downloads: true
theme: jekyll-theme-cayman
